apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - servicemonitor.yaml

# 로컬 레지스트리 주소 지정. 환경 전환 시 이 값만 변경, deployment.yaml 수정 불필요.
images:
  - name: ecomm
    newName: 192.168.45.175:5000/ecomm
    newTag: 0.0.1-SNAPSHOT
