### 헬스체크
GET http://localhost:8080/

### Todo 목록 조회
GET http://localhost:8080/todos

### Todo 생성
POST http://localhost:8080/todos
Content-Type: application/json

{
  "title": "Buy milk"
}

### Todo 단건 조회
GET http://localhost:8080/todos/1

### Todo 수정
PUT http://localhost:8080/todos/1
Content-Type: application/json

{
  "title": "Buy milk",
  "completed": true
}

### Todo 삭제
DELETE http://localhost:8080/todos/1

### 잘못된 요청 (title 누락, 400 기대)
POST http://localhost:8080/todos
Content-Type: application/json

{
  "title": ""
}

### 존재하지 않는 Todo 조회 (404 기대)
GET http://localhost:8080/todos/9999

### OpenAPI 스펙
GET http://localhost:8080/openapi.json

### Swagger UI
GET http://localhost:8080/swagger
