### 특정 장바구니 조회
GET http://localhost:8080/api/v1/carts/a1b9b31d-e73c-4112-af7c-b68530f38222
Accept: application/json
Accept-Language: ko
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJzY290dCIsInJvbGVzIjpbIlVTRVIiXSwiaXNzIjoiTW9kZXJuIEFQSSBEZXZlbG9wbWVudCB3aXRoIFNwcmluZy4uLiIsImV4cCI6MTc4ODE4OTQ5OSwiaWF0IjoxNzg4MTg4NTk5fQ.AYGKoZkbpZRGOwNAl3cCHSDw4xyhnVJj-QuOe0h43ZaACaEah4-1CMU_WzGxNziuAC9MxLxh4HWW87XYBbm4bbAHzMpzRIbrYb2BdQoNmWzOlxzhq2VHQf3DA1Wr1JLfP8YfGEIyJtdJCW_93FXAdI7Atm8dv3MSHhbuEcWaB9o54ulRWj-yHoRdma_ekFqFfHnf5nMvmjByb0vd5Y9Kle1HngWp21Vylnf5_FNWv241du0nP5eyQ3NcXy3AlATo96BREhCc6AokgXsicPNxuCRNFXGQD5fzrLmaR7W9Du8Onvh_cnrIrLsHtUebK8nIwouhavEv_M6oPGGUI0h9OobnOUsPiNh1hV63ESfNEeTg8guk-xRkiOMrP4NqW7n6edbG8XPO73FVDsExOoqYe9TVAh4NjBoviqxG0Pk6TanS7oChPjCiH9GcqAfBjap7MAIpb4Ad3-Ok9FOnBhFQD--ZmjFTMklWWdhFKqsJkEpYHx0jp9bxD_1Mf-jBZl1RGuCjWWKsQzV38rT9s4z6bMciIX-IYqv6tE6zo565sHq92sfwMr9ZzMIETE9-DSDwqC2OzDDd_MzZ0neb9n51skKEtDxi_9RzPhLhR-oQaxK0uZXdHQWLzHgGIPtGkeZoZlo7di4EWnAIwzdP7OGEL5Fz4MO-bTWAldvqlJZWpMQ

### 장바구니에 상품 추가
POST http://localhost:8080/api/v1/carts/a1b9b31d-e73c-4112-af7c-b68530f38222/items
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJzY290dCIsInJvbGVzIjpbIlVTRVIiXSwiaXNzIjoiTW9kZXJuIEFQSSBEZXZlbG9wbWVudCB3aXRoIFNwcmluZy4uLiIsImV4cCI6MTc4ODE4OTQ5OSwiaWF0IjoxNzg4MTg4NTk5fQ.AYGKoZkbpZRGOwNAl3cCHSDw4xyhnVJj-QuOe0h43ZaACaEah4-1CMU_WzGxNziuAC9MxLxh4HWW87XYBbm4bbAHzMpzRIbrYb2BdQoNmWzOlxzhq2VHQf3DA1Wr1JLfP8YfGEIyJtdJCW_93FXAdI7Atm8dv3MSHhbuEcWaB9o54ulRWj-yHoRdma_ekFqFfHnf5nMvmjByb0vd5Y9Kle1HngWp21Vylnf5_FNWv241du0nP5eyQ3NcXy3AlATo96BREhCc6AokgXsicPNxuCRNFXGQD5fzrLmaR7W9Du8Onvh_cnrIrLsHtUebK8nIwouhavEv_M6oPGGUI0h9OobnOUsPiNh1hV63ESfNEeTg8guk-xRkiOMrP4NqW7n6edbG8XPO73FVDsExOoqYe9TVAh4NjBoviqxG0Pk6TanS7oChPjCiH9GcqAfBjap7MAIpb4Ad3-Ok9FOnBhFQD--ZmjFTMklWWdhFKqsJkEpYHx0jp9bxD_1Mf-jBZl1RGuCjWWKsQzV38rT9s4z6bMciIX-IYqv6tE6zo565sHq92sfwMr9ZzMIETE9-DSDwqC2OzDDd_MzZ0neb9n51skKEtDxi_9RzPhLhR-oQaxK0uZXdHQWLzHgGIPtGkeZoZlo7di4EWnAIwzdP7OGEL5Fz4MO-bTWAldvqlJZWpMQ

{
    "id": "a0a4f044-b040-410d-8ead-4de0446aec7e",
    "quantity": 1,
    "unitPrice": 7.99
}