server.port=7634
spring.rsocket.server.port=7635

spring.cloud.stream.bindings.aircraftPositions-out-0.destination=aircraftpositions
spring.cloud.stream.bindings.aircraftPositions-out-0.content-type=application/json

spring.cloud.stream.binders.rabbit.type=rabbit
spring.cloud.stream.binders.kafka.type=kafka

# active binder is chosen per profile: see application-rabbit.properties / application-kafka.properties

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.cloud.stream.kafka.binder.brokers=localhost:9092