logging.level.root=${LOG_LEVEL:ERROR}
logging.file.name=${LOG_FILE_NAME:/C:/Users/a4336/Desktop/logs/app-qa.log}

spring.jpa.show-sql=${JPA_SHOW_URL:false}
spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL:false}

contact.phone=+91-1234567890
contact.email=prod@eazystore.com
contact.address=123 Main Street, NewYork, USA

# spring.profiles.active=prod